import { useQuery } from '@tanstack/react-query';
import { AlertTriangle, CheckCircle2, CircleHelp, LoaderCircle } from 'lucide-react';
import { Link } from 'wouter';
import { apiUrl } from '@/lib/desktop-api-base-url';

type Finding = { id: string; category: string; severity: string; title: string; summary: string; state: string; whyItMatters: string; known: string[]; unknowns: string[]; recommendedAction: string };
type Health = { counts: { needsYou: number; uncertain: number; waiting: number; resolved: number }; findings: Finding[] };

export default function ArchiveHealthPage() {
  const health = useQuery<Health>({ queryKey: ['archive-health'], queryFn: async () => { const response = await fetch(apiUrl('/api/assistant/health')); if (!response.ok) throw new Error('Archive health unavailable'); return response.json(); }, refetchInterval: 30000 });
  if (health.isLoading) return <div className="archive-panel flex min-h-[280px] items-center justify-center gap-2"><LoaderCircle size={18} className="animate-spin" /> Checking the archive…</div>;
  if (health.isError || !health.data) return <div className="archive-panel p-8 text-center"><CircleHelp className="mx-auto mb-3 text-[#a77517]" /><h1 className="archive-display text-xl font-extrabold">Archive health is unavailable.</h1><p className="mt-2 text-sm text-[#718187]">I couldn't read the latest archive findings.</p></div>;
  const groups = ['integrity', 'naming', 'metadata', 'duplicate', 'stale'];
  return <div className="mx-auto w-full max-w-5xl"><div className="mb-7"><div className="archive-mono mb-2 text-[10px] tracking-[.2em] text-[#7a9093]">ARCHIVE HEALTH</div><h1 className="archive-display text-3xl font-extrabold text-[#21303d]">What needs attention?</h1><p className="mt-2 max-w-xl text-[13px] leading-6 text-[#718087]">A calm summary of what the archive knows, what is uncertain, and what may need your decision.</p></div><div className="mb-6 grid gap-3 sm:grid-cols-3"><div className="archive-panel p-4"><div className="archive-mono text-[9px] tracking-[.15em] text-[#7f9194]">NEEDS YOU</div><div className="mt-2 text-2xl font-extrabold text-[#a9483e]">{health.data.counts.needsYou}</div></div><div className="archive-panel p-4"><div className="archive-mono text-[9px] tracking-[.15em] text-[#7f9194]">UNCERTAIN</div><div className="mt-2 text-2xl font-extrabold text-[#a77517]">{health.data.counts.uncertain}</div></div><div className="archive-panel p-4"><div className="archive-mono text-[9px] tracking-[.15em] text-[#7f9194]">RESOLVED</div><div className="mt-2 text-2xl font-extrabold text-[#39736e]">{health.data.counts.resolved}</div></div></div><div className="space-y-5">{groups.map((group) => { const findings = health.data.findings.filter((finding) => finding.category === group); return <section key={group} className="archive-panel p-5"><div className="archive-mono text-[9px] font-bold uppercase tracking-[.16em] text-[#7f9194]">{group}</div>{findings.length === 0 ? <div className="mt-3 flex items-center gap-2 text-[12px] text-[#718187]"><CheckCircle2 size={15} className="text-[#39736e]" /> Nothing needs attention here.</div> : <div className="mt-3 divide-y divide-[#e3e8e7]">{findings.map((finding) => <article key={finding.id} className="py-4 first:pt-1"><div className="flex items-start gap-3"><div className="mt-0.5">{finding.state === 'uncertain' ? <CircleHelp size={17} className="text-[#a77517]" /> : <AlertTriangle size={17} className={finding.severity === 'critical' ? 'text-[#a9483e]' : 'text-[#a77517]'} />}</div><div className="min-w-0 flex-1"><h2 className="text-[13px] font-bold text-[#43545b]">{finding.title}</h2><p className="mt-1 text-[12px] leading-5 text-[#718187]">{finding.summary}</p><p className="mt-2 text-[11px] text-[#56736f]">{finding.whyItMatters}</p>{finding.unknowns.length > 0 && <p className="mt-2 text-[11px] text-[#a77517]">Unknown: {finding.unknowns.join('; ')}</p>}<Link href={`/workload/health:${encodeURIComponent(finding.id)}?from=archive`} className="mt-3 inline-block text-[10px] font-bold tracking-[.1em] text-[#39736e]">{finding.recommendedAction === 'review' ? 'REVIEW' : 'INVESTIGATE'}</Link></div></div></article>)}</div>}</section>;})}</div></div>;
}
