import { useEffect, useState } from 'react';
import { CalendarDays, Compass, RefreshCw, Sparkles, TrendingUp } from 'lucide-react';
import { apiUrl } from '@/lib/desktop-api-base-url';

type Brief = { upcoming?: { items?: Array<any>; reason?: string | null }; recent?: Array<any>; personalContext?: { personalizedBriefing?: Array<any> }; comparisons?: { items?: Array<any> }; comparisonLimitations?: string[] };
export default function DiscoverPage() { const [data, setData] = useState<Brief | null>(null); const [loading, setLoading] = useState(true); const [error, setError] = useState('');
  const load = async () => { setLoading(true); try { const response = await fetch(apiUrl('/api/agent/research'), { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ includeUpcoming: true, includeComparisons: true }) }); if (!response.ok) throw new Error('Research unavailable'); setData(await response.json()); } catch (e) { setError(e instanceof Error ? e.message : 'Research unavailable'); } finally { setLoading(false); } };
  useEffect(() => { void load(); }, []);
  if (loading) return <div className="archive-panel flex min-h-[300px] items-center justify-center gap-2 text-[10px] tracking-[.12em] text-[#7f9194]"><RefreshCw size={15} className="animate-spin" /> BUILDING EVIDENCE BRIEF</div>;
  if (error) return <div className="archive-panel p-8 text-center"><h1 className="archive-display text-xl font-extrabold">Discovery is unavailable.</h1><p className="mt-2 text-[12px] text-[#829095]">{error}</p><button onClick={() => void load()} className="mt-4 border px-3 py-2 text-[10px] font-bold">TRY AGAIN</button></div>;
  const upcoming = data?.upcoming?.items ?? []; const recent = data?.recent ?? []; const briefing = data?.personalContext?.personalizedBriefing ?? []; const comparisons = data?.comparisons?.items ?? [];
  const Card = ({ item, label }: { item: any; label: string }) => <article className="border-t border-[#e3e8e7] py-3"><div className="flex items-start justify-between gap-3"><div><div className="text-[12px] font-bold text-[#42545b]">{item.title}</div><div className="mt-1 text-[10px] text-[#829095]">{item.itemType ?? item.candidate?.mediaType ?? 'media'} {item.year ?? item.candidate?.year ?? ''}</div></div><span className="archive-mono text-[9px] text-[#39736e]">{label}</span></div>{item.reasons?.length > 0 && <p className="mt-2 text-[10px] leading-4 text-[#718187]">{item.reasons.join(' · ')}</p>}{item.whyYou?.length > 0 && <p className="mt-2 text-[10px] leading-4 text-[#39736e]">Why you: {item.whyYou.slice(0, 2).join(' · ')}</p>}</article>;
  return <div className="mx-auto w-full max-w-6xl"><div className="mb-7 flex flex-wrap items-end justify-between gap-4"><div><div className="archive-mono mb-2 text-[10px] tracking-[.2em] text-[#7a9093]">DISCOVER / EVIDENCE</div><h1 className="archive-display text-3xl font-extrabold text-[#21303d]">Find what matters next</h1><p className="mt-2 max-w-xl text-[13px] leading-6 text-[#718087]">Upcoming media and research ranked against archive evidence, viewing history, and source confidence.</p></div><button onClick={() => void load()} className="inline-flex items-center gap-2 border px-3 py-2 text-[10px] font-bold"><RefreshCw size={13} /> REFRESH RESEARCH</button></div><div className="grid gap-5 lg:grid-cols-2"><section className="archive-panel p-5"><div className="flex items-center gap-2"><CalendarDays size={17} className="text-[#4e9690]" /><h2 className="archive-display text-lg font-extrabold">Upcoming</h2></div>{upcoming.length ? upcoming.slice(0, 12).map((item, i) => <Card key={`${item.id ?? item.key}-${i}`} item={item} label={item.provider ?? 'SOURCE'} />) : <p className="mt-4 text-[11px] text-[#829095]">{data?.upcoming?.reason ?? 'No reliable upcoming release evidence.'}</p>}</section><section className="archive-panel p-5"><div className="flex items-center gap-2"><Sparkles size={17} className="text-[#4e9690]" /><h2 className="archive-display text-lg font-extrabold">For you</h2></div>{briefing.length ? briefing.slice(0, 12).map((item, i) => <Card key={`${item.recommendationId ?? i}`} item={item} label={item.personalAffinity ?? 'RELEVANT'} />) : <p className="mt-4 text-[11px] text-[#829095]">No strong personal viewing signal is available yet.</p>}</section><section className="archive-panel p-5"><div className="flex items-center gap-2"><Compass size={17} className="text-[#4e9690]" /><h2 className="archive-display text-lg font-extrabold">Recently released</h2></div>{recent.length ? recent.slice(0, 12).map((item, i) => <Card key={`${item.id ?? item.key}-${i}`} item={item} label="RECENT" />) : <p className="mt-4 text-[11px] text-[#829095]">No reliable recent release evidence.</p>}</section><section className="archive-panel p-5"><div className="flex items-center gap-2"><TrendingUp size={17} className="text-[#a77517]" /><h2 className="archive-display text-lg font-extrabold">Research comparisons</h2></div>{comparisons.length ? comparisons.slice(0, 8).map((item, i) => <Card key={`${item.candidate?.id ?? i}`} item={item} label={item.confidence ?? 'UNCERTAIN'} />) : <p className="mt-4 text-[11px] text-[#829095]">No cross-source comparisons are available.</p>}{data?.comparisonLimitations?.length ? <p className="mt-3 border-t border-[#e3e8e7] pt-3 text-[10px] text-[#a77517]">{data.comparisonLimitations[0]}</p> : null}</section></div></div>; }
