import { useEffect, useState } from 'react';
import { Link } from 'wouter';
import { PlaySquare, RefreshCw, Save } from 'lucide-react';
import { useGetJellyfinConfig, useStartJellyfinSync, useTestJellyfinConnection, useUpdateJellyfinConfig } from '@workspace/api-client-react';

export default function JellyfinPage() {
  const { data, isLoading, refetch } = useGetJellyfinConfig(); const update = useUpdateJellyfinConfig(); const test = useTestJellyfinConnection(); const sync = useStartJellyfinSync();
  const [serverUrl, setServerUrl] = useState(''); const [token, setToken] = useState(''); const [notice, setNotice] = useState('');
  useEffect(() => { if (data) setServerUrl(data.serverUrl ?? ''); }, [data]);
  if (isLoading || !data) return <div className="archive-panel flex min-h-[260px] items-center justify-center gap-2 text-[10px] tracking-[.12em] text-[#7f9194]"><RefreshCw size={15} className="animate-spin" /> READING JELLYFIN STATUS</div>;
  const save = (event: React.FormEvent) => { event.preventDefault(); update.mutate({ data: { serverUrl, ...(token ? { apiKey: token } : {}) } }, { onSuccess: () => { setToken(''); setNotice('Configuration saved.'); refetch(); }, onError: () => setNotice('Configuration could not be saved.') }); };
  return <div className="mx-auto w-full max-w-5xl"><div className="mb-7"><div className="archive-mono mb-2 text-[10px] tracking-[.2em] text-[#7a9093]">MEDIA HOST / JELLYFIN</div><h1 className="archive-display text-3xl font-extrabold text-[#21303d]">Jellyfin configuration</h1><p className="mt-2 max-w-xl text-[13px] leading-6 text-[#718087]">Connect Jellyfin as a read-only media source, then sync its inventory into Archive Assistant.</p></div><section className="archive-panel p-5 md:p-7"><div className="flex items-center gap-3"><PlaySquare className="text-[#4e9690]" /><div><h2 className="archive-display text-lg font-extrabold">Connection</h2><p className="text-[11px] text-[#829095]">{data.configured ? 'Configuration is present.' : 'Jellyfin is not configured.'}</p></div></div><form onSubmit={save} className="mt-6 grid gap-4 md:grid-cols-2"><label><span className="archive-mono mb-2 block text-[9px] tracking-[.1em] text-[#6e8185]">SERVER URL</span><input value={serverUrl} onChange={e => setServerUrl(e.target.value)} placeholder="http://localhost:8096" className="w-full border border-[#d6dfdc] bg-[#fbfcfa] px-3 py-3 text-[12px]" /></label><label><span className="archive-mono mb-2 block text-[9px] tracking-[.1em] text-[#6e8185]">API TOKEN</span><input type="password" value={token} onChange={e => setToken(e.target.value)} placeholder={data.hasApiKey ? 'Stored — enter to replace' : 'Paste token'} className="w-full border border-[#d6dfdc] bg-[#fbfcfa] px-3 py-3 text-[12px]" /></label><div className="flex flex-wrap gap-2 md:col-span-2"><button className="inline-flex items-center gap-2 bg-[#1d2b38] px-4 py-2.5 text-[10px] font-bold tracking-[.1em] text-white"><Save size={13} /> SAVE CONFIGURATION</button><button type="button" disabled={!data.configured || test.isPending} onClick={() => test.mutate(undefined, { onSuccess: () => { setNotice('Connection verified.'); refetch(); }, onError: () => setNotice('Connection failed.') })} className="border border-[#d6dfdc] px-4 py-2.5 text-[10px] font-bold tracking-[.1em]">TEST CONNECTION</button><button type="button" disabled={!data.configured || sync.isPending} onClick={() => sync.mutate(undefined, { onSuccess: () => setNotice('Sync started.'), onError: () => setNotice('Sync could not start.') })} className="border border-[#4e9690] bg-[#eaf3ef] px-4 py-2.5 text-[10px] font-bold tracking-[.1em] text-[#39736e]">SYNC INVENTORY</button></div>{notice && <div className="text-[11px] text-[#39736e]">{notice}</div>}</form></section><Link href="/sources" className="mt-5 inline-block text-[10px] font-bold tracking-[.1em] text-[#39736e]">← BACK TO SOURCES</Link></div>;
}
