import { Link } from 'wouter';
import { Network, PlaySquare, RefreshCw } from 'lucide-react';
import { useGetIntegrationStatuses } from '@workspace/api-client-react';

export default function SourcesPage() {
  const { data, isLoading, isError, refetch } = useGetIntegrationStatuses();
  if (isLoading) return <div className="archive-panel flex min-h-[240px] items-center justify-center gap-3 text-[10px] tracking-[.12em] text-[#7f9194]"><RefreshCw size={15} className="animate-spin" /> READING SOURCE STATUS</div>;
  if (isError) return <section className="archive-panel border-l-2 border-[#d9bd77] p-6"><div className="archive-mono text-[10px] tracking-[.14em] text-[#a77517]">SOURCES / UNAVAILABLE</div><h1 className="archive-display mt-2 text-2xl font-extrabold text-[#263844]">Source status could not be read.</h1><button type="button" onClick={() => refetch()} className="mt-4 border border-[#d6dfdc] bg-white px-3 py-2 text-[10px] font-bold tracking-[.08em] text-[#53656b]">TRY AGAIN</button></section>;
  return <><div className="mb-7"><div className="archive-mono mb-2 text-[10px] tracking-[.2em] text-[#7a9093]">SYSTEM / SOURCES</div><h1 className="archive-display text-3xl font-extrabold text-[#21303d] md:text-[38px]">Connected sources</h1><p className="mt-2 max-w-xl text-[13px] leading-6 text-[#718087]">Only configured sources are expected to be operational. Unconfigured adapters remain visible as explicit foundation status, not as failed connections.</p></div><section className="archive-panel p-5 md:p-7" data-testid="panel-sources"><div className="space-y-3">{(data?.integrations ?? []).map((provider) => <div key={provider.id} className="flex items-center justify-between gap-4 border-t border-[#e3e8e7] pt-3 first:border-0 first:pt-0"><div className="flex items-center gap-3"><div className="grid h-8 w-8 place-items-center bg-[#e8efed] text-[#4e9690]">{provider.id === 'plex' ? <PlaySquare size={15} /> : <Network size={15} />}</div><div><div className="text-[12px] font-bold text-[#42545b]">{provider.name}</div><div className="mt-1 text-[10px] text-[#8b999c]">{provider.detail}</div></div></div><span className={`archive-mono text-[9px] font-bold tracking-[.08em] ${provider.configured ? 'text-[#39736e]' : 'text-[#a77517]'}`}>{provider.configured ? provider.state.toUpperCase() : 'NOT CONFIGURED'}</span></div>)}</div><Link href="/plex" className="mt-6 inline-flex items-center gap-2 border border-[#4e9690] bg-[#eaf3ef] px-3 py-2 text-[10px] font-bold tracking-[.08em] text-[#39736e]">OPEN PLEX CONFIGURATION</Link></section></>;
}
