import { useEffect, useState } from 'react';
import { Link } from 'wouter';
import { Network, PlaySquare, RefreshCw, Save } from 'lucide-react';
import { useGetIntegrationStatuses } from '@workspace/api-client-react';

type Plugin = { id: string; name: string; fields: Array<{ key: string; label: string; secret?: boolean }> };
const plugins: Plugin[] = [
  { id: 'sonarr', name: 'Sonarr', fields: [{ key: 'endpoint', label: 'URL' }, { key: 'apiKey', label: 'API key', secret: true }, { key: 'rootFolderPath', label: 'Root folder' }, { key: 'qualityProfileId', label: 'Quality profile ID' }] },
  { id: 'radarr', name: 'Radarr', fields: [{ key: 'endpoint', label: 'URL' }, { key: 'apiKey', label: 'API key', secret: true }, { key: 'rootFolderPath', label: 'Root folder' }, { key: 'qualityProfileId', label: 'Quality profile ID' }] },
  { id: 'prowlarr', name: 'Prowlarr', fields: [{ key: 'endpoint', label: 'URL' }, { key: 'apiKey', label: 'API key', secret: true }] },
  { id: 'qbittorrent', name: 'qBittorrent', fields: [{ key: 'endpoint', label: 'URL' }, { key: 'username', label: 'Username' }, { key: 'password', label: 'Password', secret: true }] },
  { id: 'mpilot', name: 'MPilot', fields: [{ key: 'endpoint', label: 'URL' }, { key: 'apiKey', label: 'API key', secret: true }] },
  { id: 'telegram', name: 'Telegram', fields: [{ key: 'apiKey', label: 'Bot token', secret: true }] },
];

function PluginConfig({ plugin, configured, onSaved }: { plugin: Plugin; configured: boolean; onSaved: () => void }) {
  const [values, setValues] = useState<Record<string, string>>({});
  const [notice, setNotice] = useState(''); const [saving, setSaving] = useState(false);
  const save = async (event: React.FormEvent) => { event.preventDefault(); setSaving(true); setNotice(''); try { const response = await fetch(`/api/integrations/config/${plugin.id}`, { method: 'PUT', headers: { 'content-type': 'application/json' }, body: JSON.stringify(values) }); const result = await response.json(); if (!response.ok) throw new Error(result.error ?? 'Configuration could not be saved.'); setValues({}); setNotice('Saved. Test the connection from the integration status panel.'); onSaved(); } catch (error) { setNotice(error instanceof Error ? error.message : 'Configuration could not be saved.'); } finally { setSaving(false); } };
  return <details className="archive-panel p-5" data-testid={`panel-plugin-config-${plugin.id}`}><summary className="flex cursor-pointer list-none items-center justify-between gap-3"><div><div className="text-[12px] font-bold text-[#42545b]">{plugin.name}</div><div className="mt-1 text-[10px] text-[#8b999c]">{configured ? 'Configuration is present. Enter only values you want to replace.' : 'Needs configuration.'}</div></div><span className={`archive-mono text-[9px] font-bold tracking-[.08em] ${configured ? 'text-[#39736e]' : 'text-[#a77517]'}`}>{configured ? 'CONFIGURED' : 'CONFIGURE'}</span></summary><form onSubmit={save} className="mt-5 grid gap-3 border-t border-[#e3e8e7] pt-5 md:grid-cols-2">{plugin.fields.map((field) => <label key={field.key} className="block"><span className="archive-mono mb-1 block text-[9px] tracking-[.1em] text-[#6e8185]">{field.label}</span><input type={field.secret ? 'password' : 'text'} value={values[field.key] ?? ''} onChange={(event) => setValues((current) => ({ ...current, [field.key]: event.target.value }))} placeholder={configured && field.secret ? 'Stored — enter to replace' : ''} className="w-full border border-[#d6dfdc] bg-[#fbfcfa] px-3 py-2.5 text-[12px] outline-none focus:border-[#4e9690]" /></label>)}<div className="flex items-center gap-3 md:col-span-2"><button disabled={saving} className="inline-flex items-center gap-2 bg-[#1d2b38] px-3 py-2.5 text-[10px] font-bold tracking-[.1em] text-white disabled:opacity-50"><Save size={13} />{saving ? 'SAVING' : 'SAVE CONFIGURATION'}</button>{notice && <span className={`text-[10px] ${notice.startsWith('Saved') ? 'text-[#39736e]' : 'text-[#c85b51]'}`}>{notice}</span>}</div></form></details>;
}

export default function SourcesPage() {
  const { data, isLoading, isError, refetch } = useGetIntegrationStatuses();
  const [config, setConfig] = useState<Array<{ id: string; configuredFields: string[]; hasSecret: boolean }>>([]);
  const readConfig = () => fetch('/api/integrations/config').then((response) => response.json()).then((value) => setConfig(value.integrations ?? []));
  useEffect(() => { void readConfig(); }, []);
  if (isLoading) return <div className="archive-panel flex min-h-[240px] items-center justify-center gap-3 text-[10px] tracking-[.12em] text-[#7f9194]"><RefreshCw size={15} className="animate-spin" /> READING SOURCE STATUS</div>;
  if (isError) return <section className="archive-panel border-l-2 border-[#d9bd77] p-6"><div className="archive-mono text-[10px] tracking-[.14em] text-[#a77517]">SOURCES / UNAVAILABLE</div><h1 className="archive-display mt-2 text-2xl font-extrabold text-[#263844]">Source status could not be read.</h1><button type="button" onClick={() => refetch()} className="mt-4 border border-[#d6dfdc] bg-white px-3 py-2 text-[10px] font-bold tracking-[.08em] text-[#53656b]">TRY AGAIN</button></section>;
  return <><div className="mb-7"><div className="archive-mono mb-2 text-[10px] tracking-[.2em] text-[#7a9093]">SYSTEM / SOURCES</div><h1 className="archive-display text-3xl font-extrabold text-[#21303d] md:text-[38px]">Connected sources</h1><p className="mt-2 max-w-xl text-[13px] leading-6 text-[#718087]">Configure optional plugins here. Secrets are masked and stored in a separate local configuration file, not the archive database.</p></div><section className="archive-panel p-5 md:p-7" data-testid="panel-sources"><div className="space-y-3">{(data?.integrations ?? []).map((provider) => <div key={provider.id} className="flex items-center justify-between gap-4 border-t border-[#e3e8e7] pt-3 first:border-0 first:pt-0"><div className="flex items-center gap-3"><div className="grid h-8 w-8 place-items-center bg-[#e8efed] text-[#4e9690]">{provider.id === 'plex' ? <PlaySquare size={15} /> : <Network size={15} />}</div><div><div className="text-[12px] font-bold text-[#42545b]">{provider.name}</div><div className="mt-1 text-[10px] text-[#8b999c]">{provider.detail}</div></div></div><span className={`archive-mono text-[9px] font-bold tracking-[.08em] ${provider.configured ? 'text-[#39736e]' : 'text-[#a77517]'}`}>{provider.configured ? provider.state.toUpperCase() : 'NOT CONFIGURED'}</span></div>)}</div><Link href="/plex" className="mt-6 inline-flex items-center gap-2 border border-[#4e9690] bg-[#eaf3ef] px-3 py-2 text-[10px] font-bold tracking-[.1em] text-[#39736e]">OPEN PLEX CONFIGURATION</Link></section><section className="mt-5 space-y-3" data-testid="panel-plugin-configurations"><div className="archive-mono px-1 text-[10px] tracking-[.14em] text-[#7f9194]">PLUGIN CONFIGURATION</div>{plugins.map((plugin) => <PluginConfig key={plugin.id} plugin={plugin} configured={Boolean(config.find((item) => item.id === plugin.id)?.configuredFields.length)} onSaved={() => void Promise.all([readConfig(), refetch()])} />)}</section></>;
}
