import { ArrowLeft, CircleAlert, CircleHelp, ExternalLink, LoaderCircle } from 'lucide-react';
import { Link } from 'wouter';
import { useGetAssistantFindingDetail } from '@workspace/api-client-react';

function stateLabel(state: string) {
  return state === 'actionable' ? 'Needs your attention' : state === 'blocked' ? 'Blocked' : state === 'uncertain' ? 'Not confirmed' : state === 'resolved' ? 'Resolved' : 'Informational';
}

function stateTone(state: string) {
  return state === 'actionable' ? 'border-[#d9bd77] bg-[#fff8e7] text-[#80652e]' : state === 'blocked' || state === 'uncertain' ? 'border-[#efd3cf] bg-[#fff5f3] text-[#8d4a45]' : 'border-[#d7e1de] bg-[#f1f7f5] text-[#39736e]';
}

function formatObservedAt(value: string | null) {
  if (!value) return 'Not recorded';
  const date = new Date(value);
  return Number.isNaN(date.getTime()) ? value : date.toLocaleString();
}

export default function FindingDetail({ findingId, backPath = '/assistant' }: { findingId: string; backPath?: string }) {
  const finding = useGetAssistantFindingDetail(findingId);
  if (finding.isLoading) return <div className="mx-auto w-full max-w-4xl"><div className="archive-panel flex min-h-[300px] items-center justify-center gap-2 p-8 text-[11px] text-[#718187]" data-testid="panel-finding-loading"><LoaderCircle size={15} className="animate-spin" /> Reading the evidence record…</div></div>;
  if (finding.isError || !finding.data) return <div className="mx-auto w-full max-w-4xl"><div className="archive-panel flex min-h-[300px] flex-col items-center justify-center p-8 text-center" data-testid="panel-finding-unavailable"><CircleHelp size={24} className="mb-3 text-[#a77517]" /><h1 className="archive-display text-xl font-extrabold">This finding could not be confirmed.</h1><p className="mt-2 max-w-md text-[12px] leading-5 text-[#718187]">The finding is not available for this local operator, or the evidence read failed. No action was taken.</p><Link href={backPath} className="mt-6 inline-flex items-center gap-2 text-[10px] font-bold tracking-[.1em] text-[#39736e]"><ArrowLeft size={13} /> BACK TO ASSISTANT</Link></div></div>;

  const detail = finding.data;
  return <div className="mx-auto w-full max-w-4xl" data-testid="finding-detail">
    <Link href={backPath} className="mb-5 inline-flex items-center gap-2 text-[10px] font-bold tracking-[.1em] text-[#39736e]" data-testid="link-finding-back"><ArrowLeft size={13} /> BACK TO ASSISTANT</Link>
    <div className="mb-7"><div className="archive-mono mb-2 text-[10px] tracking-[.2em] text-[#7a9093]">ASSISTANT / EVIDENCE RECORD</div><h1 className="archive-display text-3xl font-extrabold text-[#21303d]" data-testid="finding-title">{detail.title}</h1><p className="mt-2 max-w-2xl text-[13px] leading-6 text-[#718087]">A read-only explanation of what Archive Assistant concluded and what remains unconfirmed.</p></div>
    <section className="archive-panel mb-5 p-5 md:p-7" data-testid="panel-finding-conclusion"><div className="flex flex-wrap items-start justify-between gap-4"><div><div className="archive-mono text-[9px] tracking-[.14em] text-[#7f9194]">CONCLUSION</div><h2 className="archive-display mt-1 text-xl font-extrabold text-[#263844]">{stateLabel(detail.state)}</h2></div><span className={`border px-2.5 py-1 text-[10px] font-bold tracking-[.1em] ${stateTone(detail.state)}`} data-testid="finding-state">{detail.state.toUpperCase()}</span></div><p className="mt-5 text-[13px] leading-6 text-[#43545b]" data-testid="finding-explanation">{detail.explanation}</p><div className="mt-5 grid gap-4 border-t border-[#e3e8e7] pt-4 sm:grid-cols-3"><div><div className="archive-mono text-[9px] text-[#829095]">TYPE</div><div className="mt-1 text-[12px] font-semibold text-[#53656b]">{detail.type}</div></div><div><div className="archive-mono text-[9px] text-[#829095]">PRIORITY</div><div className="mt-1 text-[12px] font-semibold text-[#53656b]">{detail.priority}</div></div><div><div className="archive-mono text-[9px] text-[#829095]">CONFIDENCE</div><div className="mt-1 text-[12px] font-semibold text-[#53656b]" data-testid="finding-confidence">{detail.confidence}<span className="ml-1 text-[10px] font-normal text-[#829095]">(not a probability)</span></div></div></div></section>
    <section className="archive-panel mb-5 p-5 md:p-7" data-testid="panel-finding-why"><div className="archive-mono text-[9px] tracking-[.14em] text-[#7f9194]">WHY IT MATTERS</div><p className="mt-3 text-[13px] leading-6 text-[#43545b]">{detail.recommendedAction}</p><div className="mt-4 border-l-2 border-[#d9bd77] bg-[#fff8e7] p-3 text-[11px] leading-5 text-[#80652e]" data-testid="finding-freshness"><strong>Evidence freshness:</strong> {detail.freshness.label}. Observed at {formatObservedAt(detail.freshness.observedAt)}{!detail.freshness.available ? ' — no completed scan timestamp is available.' : '.'}</div></section>
    <section className="archive-panel mb-5 p-5 md:p-7" data-testid="panel-finding-evidence"><div className="archive-mono text-[9px] tracking-[.14em] text-[#7f9194]">EVIDENCE</div>{detail.evidence.length ? <div className="mt-4 divide-y divide-[#e3e8e7]">{detail.evidence.map((item, index) => <div key={`${item.sourceId ?? 'evidence'}-${index}`} className="py-4 first:pt-0 last:pb-0" data-testid={`finding-evidence-${index}`}><p className="text-[12px] leading-5 text-[#43545b]">{item.statement}</p><div className="archive-mono mt-2 text-[9px] tracking-[.04em] text-[#97a3a4]">SOURCE / {item.source} {item.sourceId ? `/ ${item.sourceId}` : ''} · {item.available ? 'AVAILABLE' : 'UNAVAILABLE'} · OBSERVED {formatObservedAt(item.observedAt)}</div></div>)}</div> : <div className="mt-4 flex gap-2 border-l-2 border-[#efd3cf] bg-[#fff5f3] p-3 text-[11px] leading-5 text-[#8d4a45]" data-testid="finding-evidence-missing"><CircleAlert size={14} className="mt-0.5 shrink-0" /> No supporting evidence was returned. This is not a negative conclusion.</div>}</section>
    <section className="archive-panel mb-5 p-5 md:p-7" data-testid="panel-finding-uncertainty"><div className="archive-mono text-[9px] tracking-[.14em] text-[#7f9194]">WHAT IS UNCERTAIN</div>{detail.uncertainty.length || detail.blockers.length ? <ul className="mt-4 space-y-3 text-[12px] leading-5 text-[#53656b]">{[...detail.blockers.map((item) => `Blocked: ${item}`), ...detail.uncertainty].map((item, index) => <li key={`${item}-${index}`} className="flex gap-2"><CircleHelp size={14} className="mt-0.5 shrink-0 text-[#a77517]" />{item}</li>)}</ul> : <p className="mt-4 text-[12px] text-[#718187]">No additional uncertainty was reported by the source read model.</p>}</section>
    <section className="archive-panel mb-5 border-l-2 border-[#4e9690] p-5 md:p-7" data-testid="panel-finding-next"><div className="archive-mono text-[9px] tracking-[.14em] text-[#7f9194]">NEXT SAFE STEP</div><h2 className="archive-display mt-1 text-lg font-extrabold text-[#263844]">{detail.recommendedAction}</h2><p className="mt-3 text-[12px] leading-5 text-[#53656b]">{detail.consequence}</p><div className="mt-5 flex flex-wrap gap-3">{detail.references.map((reference) => <Link key={`${reference.kind}-${reference.id}`} href={reference.href} className="inline-flex items-center gap-2 border border-[#d7e1de] bg-white px-3 py-2 text-[10px] font-bold tracking-[.08em] text-[#39736e]" data-testid={`link-finding-reference-${reference.kind}`}><ExternalLink size={12} /> {reference.label}</Link>)}</div></section>
  </div>;
}
